volumes:
  elo_drinks_pg_vol:

networks:
  elo_drinks_net:
    name: elo_drinks_net

services:
  elo_drinks_db:
    container_name: elo_drinks_db
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=elo_drinks
      - POSTGRES_USER=elo_drinks
      - POSTGRES_PASSWORD=strongPassword
    networks:
      - elo_drinks_net
    volumes:
      - elo_drinks_pg_vol:/var/lib/postgresql/data
